### PR TITLE
If Text::CSV_XS installed, require compatible version

### PR DESCRIPTION
**Pull request by mohawk2**
This will avoid problems like http://www.cpantesters.org/cpan/report/96bdd0c1-6bff-1014-8104-853c5b744612

### CODE REVIEW

**Comment by charsbar** [comment]
I'd rather just bump up the $XS_Version in Text::CSV as the XS module itself may have been installed via an OS packager (and in that case essential files to build (gcc, make etc) may not have been installed), but I'm not yet sure to which version. According to the Changes file, 1.39 may be a good candidate, but it may be too high for the OS package users.

By the way, putting ```BEGIN { $ENV{PERL_TEXT_CSV} = 0 }``` at the top of your test (to force Text::CSV to use the bundled Text::CSV_PP) should solve your problem.

**Comment by mohawk2** [comment]
My problem is that my module relies on your module providing a `csv` function, which it is documented as providing (it's making a promise).  Your module is currently failing to deliver on that promise if an old version of CSV_XS is there. If you want to increase the `$XS_Version`, and your module then successfully delivers on its promise, that will be fine. I don't see it as valid to ask your module's users to set environment variables so that it will work correctly.

**Comment by charsbar** [comment]
Sorry for being late. Now Text::CSV_PP passes all the tests of Text::CSV_XS 1.46, so it should be safe to update required XS version to 1.45 (actually 1.46). Merged. Thank you.

**Comment by mohawk2** [comment]
Thanks!

**Pull request merged**
