### PR TITLE
add useful example

### PR DESCRIPTION
**Pull request by mishin**
Hi makamake,
can I add example ?

### CODE REVIEW

**Comment by charsbar** [comment]
Hi, could you explain what is the actual purpose of this example (to show how to handle unicode, etc), because it might be better 1) to improve doc, or 2) to add tests, instead of adding a random example?

**Comment by mishin** [comment]
Well @charsbar. Yes , some things are not so obvious from the documentation , perhaps it makes sense to improve it , I need to think about it.

**Comment by charsbar** [comment]
Text::CSV(_PP) 1.91 stole almost all the docs from Text::CSV_XS. If you find anything missing, please raise an issue/send a pull-request to Text::CSV_XS then we'll steal the result again :) Closing for now. Thanks.

**Comment by mishin** [comment]
Well, good.

**Pull request closed without merging**
